### ISSUE TITLE
Tree arrow reverse back to father node when creating child node of the same value with father node

### ISSUE THREAD

**Issue by trandat9h** [dangchinh25/ds-visualizer#1]
Check this test case : [3, 9, 20, -2, 3, 15, 7, 8]
This test should create new child node of value 3 instead of arrow back to father of value 3

**Comment by dangchinh25** [comment]
Thank you for your suggestion. This was by design as I didn't plan to allow duplicating value in BinaryTree at first. This has been fixed in version 1.0.5.
